name: "Get & cache dependencies"
description: "Get the dependencies (via npm) and cache them"
inputs:
   enable-caching:
      description: "Decide to cache dependencies or not"
      required: false
      default: "true"
outputs:
   used-cache:
      description: "Whether the cache was used."
      value: ${{ steps.install.outputs.cache }}
runs:
   using: "composite"
   steps:
      - name: Cache dependencies
        if: inputs.enable-caching == 'true'
        id: cache
        uses: actions/cache@v3
        with:
           path: node_modules
           key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        id: install
        if: steps.cache.outputs.cache-hit != 'true' || inputs.enable-caching != 'true'
        run: |
           npm ci
           echo "cache='${{ inputs.enable-caching }}'" >> $GITHUB_OUTPUT
        shell: bash
